version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_USER}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../client/build:/usr/share/nginx/html
    depends_on:
      - backend